dist: bionic

language: java

jdk: openjdk8

services:
    - docker
    - xvfb

# skip installation step
install: true

cache:
    - $HOME/.m2

script:
    - mvn -f schoolmodel/pom.xml clean verify -Pjacoco coveralls:report
