dist: bionic
language: java
jdk: openjdk8
services:
- docker
- xvfb
install: true
cache:
- "$HOME/.m2"
- "$HOME/.sonar/cache"

addons:
  sonarcloud:
    organization: "predictabowl"
    token: $SONAR_TOKEN
   
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
- mvn -f schoolmodel/pom.xml clean verify -Pjacoco coveralls:report sonar:sonar -Dsonar.projectKey=Predictabowl_SchoolModelExercise



  
